run_id = "tora_fwd_100"

script = "src/examples/tora.jl"
project = "."

# optional: any parameters your Julia code reads from the config
[params]
controller = "/home/sam/Research/OVERTVerify.jl/nnet_files/jmlr2/controllerTora100.nnet"
ntime = 20